[project]
name = "comic-localizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.12.0",
    "ctranslate2>=4.6.0",
    "deepl>=1.25.0",
    "easyocr>=1.7.2",
    "einops>=0.8.1",
    "fugashi>=1.5.2",
    "hf-xet>=1.2.0",
    "huggingface-hub>=0.26",
    "httpx>=0.28.1",
    "jaconv>=0.4.1",
    "langcodes>=3.5.1",
    "language-data>=1.4.0",
    "lingua-language-detector>=2.1.1",
    "markdown-it-py>=4.0.0",
    "mdit-plain>=1.0.1",
    "more-itertools>=10.8.0",
    "numba==0.63.1",
    "numpy>=2.3.5",
    "openai==2.14.0",
    "opencv-python-headless>=4.11.0.86",
    "pillow>=12.0.0",
    "protobuf>=6.33.1",
    "pydantic>=2.12.5",
    "pyphen>=0.17.2",
    "pyyaml>=6.0.3",
    "rectpack>=0.2.2",
    "sacremoses>=0.1.1",
    "sentencepiece>=0.2.1",
    "transformers>=4.57.3",
    "ultralytics>=8.3.233",
    "unidic-lite>=1.0.8",
]

